services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Canada/Toronto
      - VERSION=docker
    volumes:
      - /data/docker/plex/config:/config
      - /data/media:/data/media
    restart: unless-stopped
