version: "3.2"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8085:8085 # qbittorrent (torrents)
      - 8989:8989 # Sonarr (tv)
      - 7878:7878 # Radarr (movies)
      - 9696:9696 # Prowlarr (indexers)
      - 8080:8080/tcp # go-remote-check (check VPN exit point)
      - 8888:8888/tcp # HTTP Proxy
    volumes:
      - /data/docker/arr-stack:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=expressvpn
      - OPENVPN_USER= # Your username generated
      - OPENVPN_PASSWORD= # Your password generated
      - SERVER_COUNTRIES=Netherlands # Exit country
      # Timezone for accurate log times
      - TZ=America/Toronto
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=24h
      # HTTP Proxy
      - HTTPPROXY=on

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - WEBUI_PORT=8085
    volumes:
      - /data/docker/arr-stack/qbittorrent:/config
      - /data/torrents/:/data/torrents # Needs only torrents access
    depends_on:
      - gluetun
    restart: always

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /data/docker/arr-stack/sonarr/data:/config
      - /data:/data # Needs full access to use hard links
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto # Specify a timezone to use e.g. Europe/London, this is required for Radarr
      # - UMASK_SET=022 # control permissions of files and directories created by Radarr
    volumes:
      - /data/docker/arr-stack/radarr/data:/config
      - /data:/data # Needs full access to use hard links
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /data/docker/arr-stack/prowlarr/data:/config
    restart: unless-stopped

  go-remote-check:
    # This container is used to check if the VPN is working
    # See https://github.com/rangzen/go-remote-check
    build:
      context: ../../sources/go-remote-check
    container_name: go-remote-check
    network_mode: "service:gluetun"
